name: Generate Az ps module

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  publish_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Assign version variable to package
        run: |
          $version = ./Find-MinModuleVersionNotInManifest.ps1 -moduleName Az -versionsManifestPath ./versions-manifest.json
          "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Download and zip Az ps module version ${{ env.VERSION }}
        run: ./Save-ModuleAsZip.ps1 -name Az -version ${{ env.VERSION }} -zipPath ${{ runner.temp }}/az_${{ env.VERSION }}.zip
        
      - name: Test if zip is present
        run: |
          $downloadSucceeded = Test-Path ${{ runner.temp }}/az_${{ env.VERSION }}.zip
          $downloadSucceeded
          if (!$downloadSucceeded) { exit 1 }
