name: Trigger publish

on:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  trigger_pr:
    name: Trigger "publish release" workflow
    runs-on: ubuntu-latest
    steps:
    - name: Trigger "Publish Release" workflow
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.PERSONAL_TOKEN }}
        script: |
          github.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'publish_release.yml',
            ref: 'main'
          });
